#!/bin/bash

terraform state mv 'module.aws-eks-kubernetes-cluster.aws_ec2_tag.cluster_primary_security_group["cluster-name"]' 'module.aws-eks-kubernetes-cluster[0].aws_ec2_tag.cluster_primary_security_group["cluster-name"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_ec2_tag.cluster_primary_security_group["terraform"]' 'module.aws-eks-kubernetes-cluster[0].aws_ec2_tag.cluster_primary_security_group["terraform"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_ec2_tag.cluster_primary_security_group["terraform-module"]' 'module.aws-eks-kubernetes-cluster[0].aws_ec2_tag.cluster_primary_security_group["terraform-module"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_eks_access_entry.this["cluster_creator"]' 'module.aws-eks-kubernetes-cluster[0].aws_eks_access_entry.this["cluster_creator"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_eks_access_policy_association.this["cluster_creator_admin"]' 'module.aws-eks-kubernetes-cluster[0].aws_eks_access_policy_association.this["cluster_creator_admin"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_eks_cluster.this[0]' 'module.aws-eks-kubernetes-cluster[0].aws_eks_cluster.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_openid_connect_provider.oidc_provider[0]' 'module.aws-eks-kubernetes-cluster[0].aws_iam_openid_connect_provider.oidc_provider[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_policy.cluster_encryption[0]' 'module.aws-eks-kubernetes-cluster[0].aws_iam_policy.cluster_encryption[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_role.this[0]' ' module.aws-eks-kubernetes-cluster[0].aws_iam_role.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_role_policy_attachment.cluster_encryption[0]' 'module.aws-eks-kubernetes-cluster[0].aws_iam_role_policy_attachment.cluster_encryption[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"]' 'module.aws-eks-kubernetes-cluster[0].aws_iam_role_policy_attachment.this["AmazonEKSClusterPolicy"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"]' 'module.aws-eks-kubernetes-cluster[0].aws_iam_role_policy_attachment.this["AmazonEKSVPCResourceController"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group.cluster[0]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group.cluster[0]' 
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group.node[0]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group.node[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.cluster["egress_nodes_ephemeral_ports_tcp"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.cluster["egress_nodes_ephemeral_ports_tcp"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.cluster["ingress_nodes_443"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.cluster["ingress_nodes_443"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["egress_all"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["egress_all"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_443"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_443"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_4443_webhook"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_4443_webhook"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_6443_webhook"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_6443_webhook"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_8443_webhook"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_8443_webhook"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_9443_webhook"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_9443_webhook"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_cluster_kubelet"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_cluster_kubelet"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_control_plane_all"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_control_plane_all"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_nodes_ephemeral"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_nodes_ephemeral"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_self_all"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_self_all"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_self_coredns_tcp"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_self_coredns_tcp"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["ingress_self_coredns_udp"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["ingress_self_coredns_udp"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["metrics_server_10250_eg"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["metrics_server_10250_eg"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.aws_security_group_rule.node["metrics_server_10250_ing"]' 'module.aws-eks-kubernetes-cluster[0].aws_security_group_rule.node["metrics_server_10250_ing"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.time_sleep.this[0]' 'module.aws-eks-kubernetes-cluster[0].time_sleep.this[0]'
# addons
terraform state mv 'module.eks_blueprints_addons.aws_eks_addon.this["coredns"]' 'module.eks_blueprints_addons[0].aws_eks_addon.this["coredns"]'
terraform state mv 'module.eks_blueprints_addons.aws_eks_addon.this["eks-pod-identity-agent"]' 'module.eks_blueprints_addons[0].aws_eks_addon.this["eks-pod-identity-agent"]'
terraform state mv 'module.eks_blueprints_addons.aws_eks_addon.this["kube-proxy"]' 'module.eks_blueprints_addons[0].aws_eks_addon.this["kube-proxy"]'
terraform state mv 'module.eks_blueprints_addons.aws_eks_addon.this["vpc-cni"]' 'module.eks_blueprints_addons[0].aws_eks_addon.this["vpc-cni"]'
terraform state mv 'module.eks_blueprints_addons.time_sleep.this' 'module.eks_blueprints_addons[0].time_sleep.this'
# node group
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_eks_node_group.this[0]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_eks_node_group.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_iam_role.this[0]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_iam_role.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.additional["karpenter"]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.additional["karpenter"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEC2ContainerRegistryReadOnly"]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEC2ContainerRegistryReadOnly"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEKSWorkerNodePolicy"]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEKSWorkerNodePolicy"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEKS_CNI_Policy"]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_iam_role_policy_attachment.this["AmazonEKS_CNI_Policy"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].aws_launch_template.this[0]' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].aws_launch_template.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.kms.aws_kms_alias.this["cluster"]' 'module.aws-eks-kubernetes-cluster[0].module.kms.aws_kms_alias.this["cluster"]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.kms.aws_kms_key.this[0]' 'module.aws-eks-kubernetes-cluster[0].module.kms.aws_kms_key.this[0]'
terraform state mv 'module.aws-eks-kubernetes-cluster.module.eks_managed_node_group["initial"].module.user_data.null_resource.validate_cluster_service_cidr' 'module.aws-eks-kubernetes-cluster[0].module.eks_managed_node_group["initial"].module.user_data.null_resource.validate_cluster_service_cidr'