name: Generate terraform docs
on:
  - pull_request

jobs:
  terraform-docs-generator:
    name: Generate terraform docs
    uses: truefoundry/workflows/.github/workflows/terraform-doc-generator.yml@iac-scanning
