name: Generate terraform docs
on:
  - pull_request

jobs:
  terraform-docs-generator:
    name: Generate terraform docs
    uses: truefoundry/workflows/.github/github-workflows-public/terraform-doc-generator.yml@terraform-workflows
